### ISSUE TITLE
lateinit property counts has not been initialized

### ISSUE THREAD

**Issue by rapidoo** [nbulteau/mystravastats#10]
plantage sur la visu des graphs

<img width="869" alt="image" src="https://user-images.githubusercontent.com/143260/196263441-201c7c3e-a3b4-4dd0-9451-c1b6d3b54288.png">

git pull de 17/10

**Comment by rapidoo** [comment]
kotlin.UninitializedPropertyAccessException: lateinit property counts has not been initialized
	at me.nicolas.stravastats.service.statistics.EddingtonStatistic.getNbDaysDistanceIsReached(EddingtonStatistic.kt:22)
	at me.nicolas.stravastats.service.charts.Chart.buildEddingtonNumberPlotByType(Chart.kt:64)
	at me.nicolas.stravastats.service.charts.ForAYearChart$build$plotlyPage$1.invoke(ForAYearChart.kt:73)
	at me.nicolas.stravastats.service.charts.ForAYearChart$build$plotlyPage$1.invoke(ForAYearChart.kt:23)
	at space.kscience.plotly.PlotGridKt.grid(PlotGrid.kt:59)
	at me.nicolas.stravastats.service.charts.ForAYearChart.build(ForAYearChart.kt:23)
	at me.nicolas.stravastats.service.ChartsService.buildCharts(ChartsService.kt:13)
	at me.nicolas.stravastats.ihm.MainController.generateCharts(MainController.kt:56)
	at me.nicolas.stravastats.ihm.MainView$1$1$1$3$1$3$1.invoke(MainView.kt:180)
	at me.nicolas.stravastats.ihm.MainView$1$1$1$3$1$3$1.invoke(MainView.kt:179)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt:437)
	at tornadofx.ControlsKt$action$2.handle(Controls.kt)
	at javafx.base@18.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at javafx.base@18.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18.0.1/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.base@18.0.1/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@18.0.1/javafx.scene.Node.fireEvent(Node.java:8797)
	at javafx.controls@18.0.1/javafx.scene.control.Button.fire(Button.java:203)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:208)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
	at javafx.base@18.0.1/com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
	at javafx.base@18.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at javafx.base@18.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at javafx.base@18.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at javafx.base@18.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at javafx.base@18.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at javafx.base@18.0.1/com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.base@18.0.1/javafx.event.Event.fireEvent(Event.java:198)
	at javafx.graphics@18.0.1/javafx.scene.Scene$MouseHandler.process(Scene.java:3881)
	at javafx.graphics@18.0.1/javafx.scene.Scene.processMouseEvent(Scene.java:1874)
	at javafx.graphics@18.0.1/javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2607)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
	at javafx.graphics@18.0.1/com.sun.glass.ui.View.handleMouseEvent(View.java:551)
	at javafx.graphics@18.0.1/com.sun.glass.ui.View.notifyMouse(View.java:937)
	at javafx.graphics@18.0.1/com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)

**Comment by rapidoo** [comment]
en fait en selectionnant 'Over years' c'est ok, mais ca plante si on selectionne une année precise.

**Comment by nbulteau** [comment]
Thank you @rapidoo 
Fix done
